app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Dashboard:index }

team:
    path:     /team
    defaults: { _controller: AppBundle:Team:index }

players:
    path:     /players
    defaults: { _controller: AppBundle:Player:index }

players.guards:
    path:     /players/guards
    defaults: { _controller: AppBundle:Player:guards }

players.forwards:
    path:     /players/forwards
    defaults: { _controller: AppBundle:Player:forwards }

players.centers:
    path:     /players/centers
    defaults: { _controller: AppBundle:Player:centers }

players.profile:
    path:     /player/{playerId}
    defaults: { _controller: AppBundle:Player:player }
    requirements:
            id: '\d+'

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

user.team.new:
    path:     /team/new
    defaults: { _controller: AppBundle:Dashboard:new }
    methods:  [GET, POST]

user.team.edit:
    path:     /team/{id}/edit
    defaults: { _controller: AppBundle:Dashboard:edit }
    requirements:
            id: '\d+'
    methods:  [GET, POST]

user.players:
    path:     /my-players
    defaults: { _controller: AppBundle:MyPlayers:index }
    methods:  [GET, POST]

user.players.guard:
    path:     /my-players/guards
    defaults: { _controller: AppBundle:MyPlayers:guard }
    methods:  [GET]

user.players.forward:
    path:     /my-players/forwards
    defaults: { _controller: AppBundle:MyPlayers:forward }
    methods:  [GET]

user.players.center:
    path:     /my-players/centers
    defaults: { _controller: AppBundle:MyPlayers:center }
    methods:  [GET]

pack.opening:
    path:     /pack
    defaults: { _controller: AppBundle:Pack:packOpening }
    methods:  [GET, POST]

discard.player:
    path:     /discard
    defaults: { _controller: AppBundle:MyPlayers:discardPlayer }
    methods:  [POST]

players.next:
    path:     /next
    defaults: { _controller: AppBundle:MyPlayers:playersNext }
    methods:  [POST]

players.previous:
    path:     /next
    defaults: { _controller: AppBundle:MyPlayers:playersPrevious }
    methods:  [POST]