app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Dashboard:index }

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:index }

team.new:
    path:     /admin/team/new
    defaults: { _controller: AppBundle:Team:new }

state.new:
    path:     /admin/state/new
    defaults: { _controller: AppBundle:State:new }
    methods:  [GET, POST]

division.new:
    path:     /admin/division/new
    defaults: { _controller: AppBundle:Division:new }
    methods:  [GET, POST]

stadium.new:
    path:     /admin/stadium/new
    defaults: { _controller: AppBundle:Stadium:new }
    methods:  [GET, POST]

town.new:
    path:     /admin/town/new
    defaults: { _controller: AppBundle:Town:new }
    methods:  [GET, POST]

team.new:
    path:     /admin/team/new
    defaults: { _controller: AppBundle:Team:new }
    methods:  [GET, POST]

team.edit:
    path:     /admin/team/{id}/edit
    defaults: { _controller: AppBundle:Team:edit }
    requirements:
            id: '\d+'
    methods:  [GET, POST]

player.new:
    path:     /admin/player/new
    defaults: { _controller: AppBundle:Player:new }
    methods:  [GET, POST]

player.edit:
    path:     /admin/player/{id}/edit
    defaults: { _controller: AppBundle:Player:edit }
    requirements:
            id: '\d+'
    methods:  [GET, POST]